[package]
name = "psuedo_net"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
magic-crypt = "4.0.1"
rand = "0.8.3"
rand_new = { git = "https://github.com/rust-random/rand.git", tag = "0.9.0" , package = "rand"}
rsa = "0.9.8"
